version: '3'

services:
  app:
    image: golang:latest
    container_name: golang-app
    working_dir: /app
    volumes:
      - ./app:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    command: go run main.go
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: alise_flowers_db
      POSTGRES_PASSWORD: k[zqDqLsnV
      POSTGRES_DB: alise_flowers_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Монтируем каталог для хранения данных

networks:
  default: